### ISSUE TITLE
newbie is lost 

### ISSUE THREAD

**Issue by nonomoute** [pwcremin/react-native-watson#1]
Hey pwcremin ! I really want to thank you for your effort into building rn bluemix cause I really need to add the watson api to my app. But guess what, i'm pretty new to coding and i don't understand how to perform that and failed also to run your code both on ios and android. (RN 47, expo 20, react 16). 

I just want to know if there is any chance you'll develop this project further and make it fully react native without manually linking (if that mean anything). if not, do you have some ressources to advice so i can learn how to add bluemix to rn ? 

big thanks !

**Comment by pwcremin** [comment]
I am in the middle of developing this module so I am sorry if the install wasn't smooth (and yes, I plan on implementing the entire watson sdk).  I will run through the install instructions with a fresh react app and make sure everything still works correctly.

I am waiting for Xcode 9 to be released before I make the changes that will allow for easy install with react-native link.  Has to do with creating static libs that are a swift/obj-c mix not being possible with < Xcode 9

**Comment by nonomoute** [comment]
oh ! that’s a very exciting and awesome news !! :)  I’ll therefore wait for the new version of Xcode and the update of your repo 👍  

anyway, you've made my day ! good luck !!

**Comment by pwcremin** [comment]
Everything should work fine, but there was one missing installation step.  I added the below section to the installation instructions for iOS.  I didn't re-test Android installation, but it should work fine with react-native link.

 ------

Add the Watson Frameworks to your project

Drag-and-drop the built frameworks into your Xcode project (put them in a Frameworks group for better management). You will also need to click on your project in Xcode and go to the General section. Add all of the frameworks to Embedded Binaries.

Note, before you can upload to itunesconnect your will need to strip unwanted architectures from the frameworks. This is done easily with a build script. See the following link for instructions: http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/

**Comment by pwcremin** [comment]
nonomoute, can you try the install again, with the new instructions, and let me know what issues you are having?
