### ISSUE TITLE
TextToSpeech.synthesize() blocking main ui thread

### ISSUE THREAD

**Issue by jin3lee** [pwcremin/react-native-watson#12]
Hi, 

Can you check out my pull request when you have time?
I created a pull request to use an async task to run the synthesize() on a separate thread to prevent blocking of the main thread.

Btw, gj on this repo, It's very easy to implement!

**Comment by pwcremin** [comment]
Great changes and great code.  Thank you!

**Comment by jin3lee** [comment]
thanks!
