### ISSUE TITLE
Update 'react-native-bluemix' references in your documentation.

### ISSUE THREAD

**Issue by maderesponsively** [pwcremin/react-native-watson#6]

**Comment by pwcremin** [comment]
Thank you!  fixed in 1.5.0.   Note that you need to specify the watson-developer-cloud version in your Cartfile now, and the names for the ios files have changed (all in the README)

**Comment by pwcremin** [comment]
Thanks you - fixed.  Please note that ios installation instructions have changed.  You much now specify a version in your Cartfile and the filenames are updated.
