### ISSUE TITLE
Issue running run-android

### ISSUE THREAD

**Issue by smckay123** [pwcremin/react-native-watson#7]
Started a new project - react-native init test; cd test; npm install react-native-watson; react-native link; react-native run-android and am getting:

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-watson'.
      > Could not resolve all dependencies for configuration ':react-native-watson:_debugPublishCopy'.
         > Could not find com.android.support:appcompat-v7:26.0.0.
           Searched in the following locations:
               file:/Users/smckay/Library/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/26.0.0/appcompat-v7-26.0.0.pom
               file:/Users/smckay/Library/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/26.0.0/appcompat-v7-26.0.0.jar
               file:/Users/smckay/git/havyn-mobile/havynMobile/android/sdk-manager/com/android/support/appcompat-v7/26.0.0/appcompat-v7-26.0.0.jar
           Required by:
               havynMobile:react-native-watson:unspecified > com.facebook.react:react-native:0.49.5

> react-native --version 
react-native-cli: 2.0.1
react-native: 0.49.5

Android SDK: 2.3.3

Any help would be appreciated.

**Comment by pwcremin** [comment]
In the build.gradle for your app set the below:
minSdkVersion 19
targetSdkVersion 26

These versions are required by the Watson developer cloud for android.  Below is a snippet from my app build.gradle example project (which I should stick into the repo):

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.2"

    defaultConfig {
        applicationId "com.rnwatson"
        minSdkVersion 26
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
