### ISSUE TITLE
Not able to find 'Use Services or APIs'

### ISSUE THREAD

**Issue by AgNm** [pwcremin/react-native-watson#8]
You have mentioned the below steps in the readme:

Create a service instance:
From the Dashboard, select "Use Services or APIs".
Select the service you want to use.
Click "Create".

But I am not able to find "Use Services or APIs" on Dashboard https://www.ibm.com/cloud/

Where is it? Can you please share screenshot for same.

**Comment by pwcremin** [comment]
The web page is always changing.  Hard to keep up.  Try this;
1. Log in
2. Select "Catalog" on the top right
3. On the left hand side, under "Platform", select "Watson"
4. Choose the Watson server you want
